config/routes.rb
Radai::Application.routes.draw do

  # Shared domain routes
  get "taisykles" => "static#eula", as: "eula"
  get "privatumas" => "static#privacy", as: "privacy"
  get "atsiliepimai" => "feedback#leave", as: "feedback_leave"
  post "atsiliepimai" => "feedback#leave_submit", as: "feedback_leave_post"

  # Subdomains
  constraints subdomain: /statybos/ do
    get "paieska" => "search#index", as: "search"
    devise_for :users
    match "registracija-sekminga" => "specialist#create_complete"
    get "specialistas/naujas" => "specialist#new", as: "new_specialist"
    post "specialistas" => "specialist#create", as: "create_specialist"
    get "profilis" => "specialist#edit", as: "edit_specialist"
    put "profilis" => "specialist#update", as: "update_specialist"
    get "specialistas/:id/:title_slug" => "specialist#show", as: "specialist_slug"
    get "specialistas/:id" => "specialist#show", as: "specialist"
    root to: "home#index"
  end

  constraints subdomain: "manage" do
    ActiveAdmin.routes(self)
    devise_for :admin_users, ActiveAdmin::Devise.config
  end

  constraints subdomain: false do
    root to: "index#list"
  end

  match '*path' => 'index#missing'

end

app/models/specialist.rb
# coding: utf-8
require 'search_params'
class Specialist < ActiveRecord::Base

  scope :desc, order("updated_at DESC")
  scope :primary_service_first, order('`specialist_services`.`primary` DESC')

  acts_as_gmappable
  geocoded_by :full_address
  reverse_geocoded_by :latitude, :longitude
  before_validation :update_geocode


  attr_accessible :user,
                  :user_id,
                  :service_types,
                  :service_type_select,
                  :extra_services_select,
                  :specialist_services,
                  :latitude,
                  :longitude,
                  :about,
                  :email,
                  :phone,
                  :title,
                  :website,
                  :full_address,
                  :show_email,
                  :show_phone

  belongs_to :user

  has_many :specialist_services
  has_many :service_types,
           through: :specialist_services

  validate :contact_privacy, :service_limit

  validates :full_address,
            presence: true

  validates :latitude,
            presence: true

  validates :specialist_services,
            one_primary_service: true

  validates :phone,
            numericality: true,
            length: {minimum: 8, maximum: 11}

  validates :website,
            url: true

  validates :title,
            presence: true,
            length: {minimum: 2, maximum: 140}

  def title_slug
    if title.present?
      title.downcase.strip
        .gsub(/\s+/, '-')
        .gsub(/[Ąą]/, 'a')
        .gsub(/[Čč]/, 'c')
        .gsub(/[ĘĖęė]/, 'e')
        .gsub(/[Įį]/, 'i')
        .gsub(/[Šš]/, 's')
        .gsub(/[ŲŪųū]/, 'u')
        .gsub(/[Žž]/, 'z')
        .gsub(/[^\w-]/, '')
    end
  end

  def og_description
    og_desc = '' << primary_service.title
    if extra_services.length > 0
      og_desc << ', '
      og_desc << extra_services.collect{ |s| s.title }.join(', ')
    end
    og_desc << '.'
  end

  def phone=(phone)
    phone = phone.gsub(/[^0-9]/, '') unless phone.nil?
    super(phone)
  end

  def contact_privacy
    unless (self.show_phone or self.show_email)
      errors.add(:privacy_settings, I18n.translate(
          'app.specialist.privacy_settings_error'))
    end
  end

  def service_limit
    if self.extra_services.length > 5
      errors.add(:extra_services, I18n.translate(
          'app.specialist.extra_services_size_error'))
    end
  end

  def self.search_for(search_params)
    if search_params.example.extra_services.any?
      results = self.page(search_params.page)
        .joins(:specialist_services)
        .group("specialists.id")
        .where("specialist_services.service_type_id in (?)", 
               search_params.service_types).primary_service_first
    end
    unless search_params.example.full_address.blank?
      if results
        results = results.near(search_params.example, search_params.radius).desc
      else
        results = self.page(search_params.page)
            .near(search_params.example, search_params.radius).desc
      end
    end
    if results
      return results
    else
        items = Specialist.desc.page(search_params.page).per(30)
        Kaminari::PaginatableArray.new(
            items.to_a,
            limit: items.limit_value,
            offset: items.offset_value,
            total_count: items.total_count)
      #end
    end
  end

  def primary_service
    primary = self.specialist_services.find_by_primary(true)
    if primary
      return primary.service_type
    else
      raise "No primary service for #{self}"
    end
  end

  def extra_services
    self.specialist_services.reject {|s| s.primary }.collect { |s| s.service_type }
  end

  def has_extra_services?
    self.specialist_services.length > 1 #count goes to db while length checks local array
  end

  def gmaps
    true
  end

  def gmap4rails_address
    self.full_address
  end

  def service_type_select=(id)
    unless id.blank?
      id = id.to_i
      # remove current primary services
      self.specialist_services.each do |s|
        if s.primary or s.service_type_id == id
          self.specialist_services.delete(s)
          break
        end
      end
      self.specialist_services.build(primary: true, service_type_id: id)
    end
  end

  def service_type_select
    self.specialist_services.each do |s|
      if s.primary
        return s.service_type_id
      end
    end
  end

  def extra_services_select=(ids)
    current_ids = []
    primary_id = nil
    self.specialist_services.each do |s|
      if s.primary
        # Remove accidental dupes?
        unless primary_id.nil?
          logger.error "Duplicate primary service! #{self.specialist_services.to_yaml}"
          self.specialist_services.delete(s) unless primary_id.nil?
        end
        primary_id = s.service_type_id.to_s
        next
      end
      unless ids.include?(s.service_type_id.to_s)
        self.specialist_services.delete(s)
      else
        current_ids.append(s.service_type_id.to_s)
      end
    end
    ids.each do |id|
      next if id.to_s == primary_id.to_s
      unless current_ids.include?(id)
        self.specialist_services.build(service_type_id: id)
      end
    end
  end

  def extra_services_include?(id)
    self.specialist_services.collect {|s| s.service_type_id unless s.primary }.include?(id)
  end

  def update_geocode
    unless latitude.present? or latitude_changed?
      should = full_address_changed? 
    end
    if should
      Rails.logger.warn("Geocoding in backend!: #{self}")
      geocode
    end
  end

end

app/controllers/specialist_controller.rb
# coding: utf-8
class SpecialistController < ApplicationController

  def index
    redirect_to action: "new"
  end

  def show
    @menu_item = "search"
    @specialist = Specialist.find(params[:id])
    if params[:title_slug] != @specialist.title_slug
      redirect_to action: "show", id: @specialist.id, title_slug: @specialist.title_slug
      return
    end
    @map_markers = @specialist.to_gmaps4rails do |obj, marker|
      marker.infowindow render_to_string(
                            partial: "shared/map_marker",
                            locals: {
                                object: obj,
                                search_address: ''
                            })
      marker.title obj.title
    end
  end

  def new
    @specialist = Specialist.new(
        user: User.new,
        show_phone: true,
        show_email: true
    )
  end

  def create
    unless params[:specialist].has_key?("extra_services_select")
      params[:specialist][:extra_services_select] = []
    end
    @specialist = Specialist.new(params[:specialist])
    @specialist.user = User.new(params[:user])

    specialist_valid = @specialist.valid?
    user_valid = @specialist.user.valid?
    if specialist_valid and user_valid
      @specialist.save()
      sign_in @specialist.user
      redirect_to action: "create_complete"
    else
      @specialist.user ||= User.new
      render action: "new"
    end
  end

  def edit
    @specialist = current_user.specialist
  end

  def update
    unless params[:specialist].has_key?("extra_services_select")
      params[:specialist][:extra_services_select] = []
    end
    @specialist = current_user.specialist
    if @specialist.update_attributes params[:specialist]
      flash[:notice] = t('app.save.success')
    end
    render action: "edit"
  end

  def create_complete
    @specialist = current_user.specialist
  end
end

app/helpers/specialist_helper.rb
module SpecialistHelper
end

app/views/specialist/_edit.html.erb
<legend>Atliekami darbai</legend>

<div class="control-group">
  <label class="control-label" for="todo">Pagrindinė paslauga</label>
  <div class="controls">
    <%= f.select :service_type_select, service_types(), { include_blank: "-- Pasirinkite --" } %>
  </div>
</div>

<div class="control-group">
  <label class="control-label" for="todo">Kitos paslaugos</label>
  <div class="controls">
    <% unless @specialist.has_extra_services? %>
        <a id="show-checkboxes" class="btn" href="#">Pridėti daugiau paslaugų</a>
    <% end %>
    <div id="checkboxes" <% unless @specialist.has_extra_services? %>class="hide"<% end %>>

      <% ServiceType.order("title").all.each do |s_type| %>
          <label class="checkbox"><%= s_type.title %>
            <%= check_box_tag "specialist[extra_services_select][]", s_type.id,
                              @specialist.extra_services_include?(s_type.id) %>
          </label>
      <% end %>
    </div>
    <%#<%= f.collection_select :extra_services_select, ServiceType.all, :id, :title, {}, multiple: true, size: 10 %>
  </div>
</div>

<legend>Prisistatymas</legend>

<div class="control-group">
  <label class="control-label" for="todo">Vardas ir pavardė</label>
  <div class="controls">
    <%= f.text_field :title, class: "input-block-level" %>
  </div>
</div>

<div class="control-group">
  <label class="control-label" for="todo">Prisistatymas</label>
  <div class="controls">
    <%= f.text_area :about, rows: "5", class: "input-block-level" %>
  </div>
</div>

<legend>Kontaktiniai duomenys</legend>

<div class="control-group">
  <label class="control-label" for="todo">Adresas</label>
  <div class="controls">
    <%= f.text_field :full_address,
                     placeholder: "Pvz.: Pilaitė, Vilnius",
                     class: "input-block-level" %>
    <%= f.hidden_field :latitude %>
    <%= f.hidden_field :longitude %>
  </div>
</div>

<div id="profile-map" class="control-group <% if @specialist.full_address.blank? or @specialist.latitude.blank? %>hide<% end %>">
  <label class="control-label"></label>
  <div class="controls">
  <%= gmaps(markers: { data: @specialist.to_gmaps4rails },
            map_options: { detect_location: false,
                           center_on_user: false,
                           language: 'lt',
                           hl: 'lt',
                           region: 'lt',
                           class: "profile_map",
                           auto_zoom: false,
                           zoom: 10}) %>
  </div>
</div>


<div class="control-group">
  <label class="control-label" for="todo">Telefono numeris</label>
  <div class="controls">
    <%= f.phone_field :phone, placeholder: "Pvz: 37011122222" %>
  </div>
</div>

<div class="control-group">
  <label class="control-label" for="todo">Interneto svetainė</label>
  <div class="controls">
    <%= f.text_field :website, class: "input-block-level" %>
  </div>
</div>

<legend>Privatumo nustatymai</legend>
<div class="control-group">
  <label class="control-label"></label>
  <div class="controls">
    <label class="checkbox">Viešinti el. pašto adresą
      <%= f.check_box :show_email %>
    </label>
  </div>
  <div class="controls">
    <label class="checkbox">Viešinti telefono numerį
      <%= f.check_box :show_phone %>
    </label>
  </div>
</div>

app/views/specialist/create_complete.html.erb
<div class="container">
    <div class="well">
      <legend><%= title "Registracija sėkminga" %></legend>
      <p>
        Kelių minučių bėgyje adresu <code><%= @specialist.user.email %></code> gausite instrukcijas,
        kaip patvirtinti paskyros registraciją. Tą galite padaryti per 2 dienas.
      </p>
      <p>
        Jau dabar galite save surasti <%= link_to "paieškoje", search_path %>. Sėkmės!
      </p>
    </div>
</div>

app/views/specialist/edit.html.erb
<div class="container">
  <div class="row">
    <div class="span7">
      <% title "Specialisto profilis" %>
      <%= form_for @specialist, html: {class: "form-horizontal well"}, url: edit_specialist_path do |f| %>
        <%= render "shared/form_errors", object: @specialist, f: f %>
        <%= render partial: "edit", locals: {specialist: @specialist, f: f} %>

        <div class="form-actions">
          <%= submit_tag "Išsaugoti", class: "btn btn-success btn-large" %>
        </div>
      <% end %>
    </div>
    <div class="span5">
      <div class="well">
        <legend>Susiję veiksmai</legend>
        <%= link_to specialist_slug_path(@specialist, @specialist.title_slug) do %>
          <i class="icon-user"></i> Profilio peržiūra
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/specialist/new.html.erb
<div class="container">
  <h1><%= title "Specialisto registracija" %></h1>
  <div class="row">
    <div class="span7">
      <%= form_for @specialist, html: {class: "form-horizontal well"}, url: create_specialist_path do |f| %>

          <% if @specialist.errors.any? or @specialist.user.errors.any? %>
          <div class="alert alert-error">
            <h3>Ištaisykite šias klaidas:</h3>

            <ul>
              <% @specialist.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
              <% @specialist.user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
          <%= render partial: "edit", locals: {specialist: @specialist, f: f} %>


          <%= fields_for @specialist.user do |user_f| %>

              <legend>Prisijungimas</legend>

              <div class="control-group">
                <label class="control-label" for="todo">El. paštas</label>
                <div class="controls">
                  <%= user_f.text_field :email, class: "input-block-level" %>
                </div>
              </div>

              <div class="control-group">
                <label class="control-label" for="todo">Slaptažodis</label>
                <div class="controls">
                  <%= user_f.password_field :password, class: "input-block-level" %>
                </div>
              </div>

          <% end %>

          <div class="form-actions">
            <%= submit_tag "Registruotis", class: "btn btn-success btn-large" %>
          </div>
      <% end %>
    </div>
    <div class="span5">
      <div class="well">

        <legend>Susiję veiksmai</legend>

          <%= link_to "Specialisto prisijungimas", new_session_path(:user) %><br />
          <%= link_to "Pamiršote slaptažodį?", new_password_path(:user) %><br />
          <%= link_to "Negavote el. pašto su paskyros patvirtinimo instrukcijomis?", new_confirmation_path(:user) %><br />

      </div>
    </div>

  </div>
</div>

app/views/specialist/show.html.erb
<% opengraph title: "#{@specialist.title} - Radai Statybos",
             description: @specialist.og_description() %>
<div class="container specialist-page">
  <div class="row">
    <div class="span6 specialist-info">
      <h2><%= title @specialist.title %></h2>
      <legend>Kontaktinė informacija</legend>
      <div class="info-block">
        <div>
          <i class="icon-map-marker"></i> <%= @specialist.full_address %>
        </div>
        <% if @specialist.show_phone %>
          <div>
            <i class="icon-phone"></i> <%= @specialist.phone %>
          </div>
        <% end %>
        <% unless @specialist.user.nil? %>
          <% if @specialist.show_email %>
            <div>
              <i class="icon-envelope"></i> <%= link_to @specialist.user.email, "mailto:#{@specialist.user.email}" %>
            </div>
          <% end %>
        <% end %>
        <% unless @specialist.website.blank? %>
          <div>
            <i class="icon-link"></i> <%= link_to @specialist.website.gsub(/^https?:\/\/(www.)?/, ''), @specialist.website %>
          </div>
        <% end %>
      </div>
      <legend>Atliekami darbai</legend>
      <div class="info-block">
        <div>
          <i class="icon-star"></i> <%= @specialist.primary_service.title %>
        </div>
        <% @specialist.extra_services.each do |s| %>
          <div>
            <i class="icon-ok"></i> <%= s.title %>
          </div>
        <% end %>
      </div>
      <% unless @specialist.about.blank? %>
        <legend>Prisistatymas</legend>
        <div class="info-block about">
          <%= markdown(@specialist.about) %>
        </div>
      <% end %>
      <a name="atsiliepimai">
      <legend>Atsiliepimai ir rekomendacijos</legend>
      <div class="info-block">
        <div class="like">
          <div class="fb-like" data-send="true" data-width="570" data-show-faces="false" data-action="like"></div>
        </div>
        <div class="fb-comments" data-href="<%= request.protocol + request.host_with_port %><%= url_for specialist_slug_path(@specialist.id, @specialist.title_slug) %>" data-num-posts="2" data-width="570"></div>
      </div>
    </div>
    <div class="span6">
      <%= gmaps(markers: { data: @map_markers },
                map_options: { detect_location: false,
                               center_on_user: false,
                               language: 'lt',
                               hl: 'lt',
                               region: 'lt',
                               class: "specialist_view_map",
                               auto_zoom: false,
                               zoom: 7}) %>
    </div>
  </div>
</div>