config/routes.rb
Radai::Application.routes.draw do

  # Shared domain routes
  get "taisykles" => "static#eula", as: "eula"
  get "privatumas" => "static#privacy", as: "privacy"
  get "atsiliepimai" => "feedback#leave", as: "feedback_leave"
  post "atsiliepimai" => "feedback#leave_submit", as: "feedback_leave_post"

  # Subdomains
  constraints subdomain: /statybos/ do
    get "paieska" => "search#index", as: "search"
    devise_for :users
    match "registracija-sekminga" => "specialist#create_complete"
    get "specialistas/naujas" => "specialist#new", as: "new_specialist"
    post "specialistas" => "specialist#create", as: "create_specialist"
    get "profilis" => "specialist#edit", as: "edit_specialist"
    put "profilis" => "specialist#update", as: "update_specialist"
    get "specialistas/:id/:title_slug" => "specialist#show", as: "specialist_slug"
    get "specialistas/:id" => "specialist#show", as: "specialist"
    root to: "home#index"
  end

  constraints subdomain: "manage" do
    ActiveAdmin.routes(self)
    devise_for :admin_users, ActiveAdmin::Devise.config
  end

  constraints subdomain: false do
    root to: "index#list"
  end

  match '*path' => 'index#missing'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :specialist
  # attr_accessible :title, :body

  has_one :specialist, dependent: :destroy

end

app/views/users/shared/_links.erb
<div class="well">

<legend>Susiję veiksmai</legend>

<%- if controller_name != 'sessions' %>
  <%= link_to "Specialisto prisijungimas", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Specialisto registracija", new_specialist_path %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Pamiršote slaptažodį?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Negavote el. pašto su paskyros patvirtinimo instrukcijomis?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Negavote paskyros atrakinimo instrukcijų?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Prisijunkite su #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>
</div>