config/routes.rb
Radai::Application.routes.draw do

  # Shared domain routes
  get "taisykles" => "static#eula", as: "eula"
  get "privatumas" => "static#privacy", as: "privacy"
  get "atsiliepimai" => "feedback#leave", as: "feedback_leave"
  post "atsiliepimai" => "feedback#leave_submit", as: "feedback_leave_post"

  # Subdomains
  constraints subdomain: /statybos/ do
    get "paieska" => "search#index", as: "search"
    devise_for :users
    match "registracija-sekminga" => "specialist#create_complete"
    get "specialistas/naujas" => "specialist#new", as: "new_specialist"
    post "specialistas" => "specialist#create", as: "create_specialist"
    get "profilis" => "specialist#edit", as: "edit_specialist"
    put "profilis" => "specialist#update", as: "update_specialist"
    get "specialistas/:id/:title_slug" => "specialist#show", as: "specialist_slug"
    get "specialistas/:id" => "specialist#show", as: "specialist"
    root to: "home#index"
  end

  constraints subdomain: "manage" do
    ActiveAdmin.routes(self)
    devise_for :admin_users, ActiveAdmin::Devise.config
  end

  constraints subdomain: false do
    root to: "index#list"
  end

  match '*path' => 'index#missing'

end

app/views/shared/_analytics.html.erb
<% if Rails.env.production? %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '<%= asset %>']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
<% else %>
  <!-- Analytics skipped in dev mode. Asset: <%= asset %> -->
<% end %>

app/views/shared/_flashes.erb
<% if flash %>
  <div class="container">
    <div class="row">
      <div class="span12">
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <%= flash[:notice] %>
          </div>
        <% end %>
        <% if flash[:error] %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <%= flash[:error] %>
          </div>
        <% end %>
        <% if flash[:alert] %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="span4">
        <p>© 2011 - <%= Time.now.year %> <%= link_to "Radai", root_url(subdomain: false) %></p>
        <div class="fb-like" data-href="<%= request.protocol + request.host_with_port %>" data-send="true" data-width="450" data-show-faces="true"></div>
      </div>
      <div class="span8 links">
        <%= link_to "Naudojimosi taisyklės", eula_path %>
        <span class="separator"></span>
        <%= link_to "Privatumo politika", privacy_path %>
        <span class="separator"></span>
        <%= link_to "Susisiekite", feedback_leave_path %>
      </div>
    </div>
  </div>
</footer>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/lt_LT/all.js#xfbml=1&appId=109122215868436";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
    <div class="alert alert-error">
      <h3>Ištaisykite šias klaidas:</h3>

      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_head.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="google-site-verification" content="sC3P4SSjaU0lieyIfz9lk1oeUicGXMeMTpRDuOfwOvc" />

<%= stylesheet_link_tag    "application", :media => "all" %>
<%= include_gon %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- Le fav and touch icons -->
<%=  favicon_link_tag %>
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">

<% unless content_for?(:opengraph) %>
  <% opengraph title: "Radai",
               description: "Mūsų tikslas - skatinti žmonių verslumą, kurti šaunias įvairių veiklos sričių bendruomenes, padėti žmonėms susirasti darbų bei gerų specialistų.",
               url: "#{request.protocol}#{request.host_with_port}" %>
<% end %>
<%= yield(:opengraph) %>

app/views/shared/_map_marker.html.erb
<div class="map-marker-info">
  <div class="title">
    <%= link_to "##{object.id}" do %>
      <i class="icon-user"></i> <strong><%= object.title %></strong>
    <% end %>
  </div>
  <hr/>
  <div>
    <i class="icon-map-marker"></i> <%= object.full_address %>
    <% unless search_address.blank? %>
      (<%=  object.distance_from(search_location).round(2) %> km)
    <% end %>
  </div>
  <% if object.show_phone %>
    <div>
      <i class="icon-phone"></i> <%= object.phone %>
    </div>
  <% end %>
  <% unless object.user.nil? %>
    <% if object.show_email %>
      <div>
        <i class="icon-envelope"></i> <%= link_to object.user.email, "mailto:#{object.user.email}" %>
      </div>
    <% end %>
  <% end %>
  <% unless object.website.blank? %>
    <div>
      <i class="icon-link"></i> <%= link_to object.website.gsub(/^https?:\/\/(www.)?/, ''), object.website %>
    </div>
  <% end %>
  <hr />
  <div>
    <i class="icon-star"></i> <%= object.primary_service.title %>
  </div>
  <% object.extra_services.each do |s| %>
    <div>
      <i class="icon-ok"></i> <%= s.title %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "brand" do %>
        <%= image_tag 'shared/radai-logo.png', width: 32, height: 32, alt: 'Radai' %> Radai Statybos
      <% end %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <%= menu_item "search" do %>
            <%=  link_to search_path do %>
              <i class="icon-search"></i>Paieška</a>
            <% end %>
          <% end %>
          <%= menu_item "specialist" do %>
            <% unless current_user %>
                <%= link_to new_specialist_path do %>
                  <i class="icon-plus"></i> Specialisto registracija
                <% end %>
            <% else %>
                <%= link_to edit_specialist_path do %>
                  <i class="icon-user"></i> Specialisto profilis
                <% end %>
            <% end %>
          <% end %>
          <%= menu_item "feedback" do %>
            <%=  link_to feedback_leave_path do %>
              <i class="icon-bullhorn"></i>Palikti atsiliepimą</a>
            <% end %>
          <% end %>
        </ul>
        <ul class="nav pull-right">
          <li class="divider-vertical"></li>
          <% if current_user %>
            <%= menu_item "devise::registrations", "dropdown" do %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <i class="icon-caret-down"></i></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to edit_user_registration_path do %>
                    <i class="icon-edit"></i> Prisijungimo nustatymai
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="icon-signout"></i> Atsijungti
                  <% end %>
                </li>
              </ul>
            <% end %>
          <% else %>
            <%= menu_item "devise::sessions" do %>
              <%= link_to new_user_session_path do %>
                <i class="icon-signin"></i> Prisijungti
              <% end %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_opengraph.html.erb
<meta property="og:title" content="<%= title ||= "Radai" %>" />
<% unless description.nil? %>
  <meta property="og:description" content="<%= description %>" />
<% end %>
<meta property="og:type" content="<%= type ||= "website" %>"/>
<meta property="og:url" content="<%= url ||= "#{request.protocol}#{request.host_with_port}#{request.fullpath}" %>" />
<meta property="og:image" content="<%= image ||= "#{request.protocol}#{request.host_with_port}#{asset_path('shared/radai-og.png')}" %>" />

app/views/shared/_specialist_card.html.erb
<div class="specialist-card" data-id="<%= object.id %>" data-slug="<%= object.title_slug %>">
  <a name="<%= object.id %>"></a>
  <legend>
    <%= link_to specialist_slug_path(object.id, object.title_slug) do %>
      <i class="icon-user"></i> <%= object.title %>
    <% end %>
  </legend>
  <div class="row-fluid">
    <div class="span6 contact-info">
      <div>
        <i class="icon-map-marker"></i> <%= object.full_address %>
        <% unless search_address.blank? %>
          (<%=  object.distance_from(search_location).round(2) %> km)
        <% end %>
      </div>
      <% if object.show_phone %>
        <div>
          <i class="icon-phone"></i> <%= object.phone %>
        </div>
      <% end %>
      <% unless object.user.nil? %>
        <% if object.show_email %>
          <div>
            <i class="icon-envelope"></i> <%= link_to object.user.email, "mailto:#{object.user.email}" %>
          </div>
        <% end %>
      <% end %>
      <% unless object.website.blank? %>
        <div>
          <i class="icon-link"></i> <%= link_to object.website.gsub(/^https?:\/\/(www.)?/, ''), object.website %>
        </div>
      <% end %>
      <span class="like-count">
        <i class="icon-thumbs-up"></i> <%= link_to specialist_slug_path(object.id, object.title_slug) do %>
           <span class="likes-<%= object.id %>">0</span>
        <% end %>
      </span>
      <span class="comment-count">
        <i class="icon-comment"></i> <%= link_to specialist_slug_path(object.id, object.title_slug) do %>
           <span class="comments-<%= object.id %>">0</span>
        <% end %>
      </span>
    </div>
      <div class="span6 service-list">
        <div>
          <i class="icon-star"></i> <%= object.primary_service.title %>
        </div>
        <% object.extra_services.each do |s| %>
          <div>
            <i class="icon-ok"></i> <%= s.title %>
          </div>
        <% end %>
      </div>
  </div>
  <% unless object.about.blank? %>
    <div class="about">
      <%= markdown(object.about) %>
    </div>
  <% end %>
</div>