config/routes.rb
Radai::Application.routes.draw do

  # Shared domain routes
  get "taisykles" => "static#eula", as: "eula"
  get "privatumas" => "static#privacy", as: "privacy"
  get "atsiliepimai" => "feedback#leave", as: "feedback_leave"
  post "atsiliepimai" => "feedback#leave_submit", as: "feedback_leave_post"

  # Subdomains
  constraints subdomain: /statybos/ do
    get "paieska" => "search#index", as: "search"
    devise_for :users
    match "registracija-sekminga" => "specialist#create_complete"
    get "specialistas/naujas" => "specialist#new", as: "new_specialist"
    post "specialistas" => "specialist#create", as: "create_specialist"
    get "profilis" => "specialist#edit", as: "edit_specialist"
    put "profilis" => "specialist#update", as: "update_specialist"
    get "specialistas/:id/:title_slug" => "specialist#show", as: "specialist_slug"
    get "specialistas/:id" => "specialist#show", as: "specialist"
    root to: "home#index"
  end

  constraints subdomain: "manage" do
    ActiveAdmin.routes(self)
    devise_for :admin_users, ActiveAdmin::Devise.config
  end

  constraints subdomain: false do
    root to: "index#list"
  end

  match '*path' => 'index#missing'

end

app/controllers/feedback_controller.rb
# coding: utf-8
class FeedbackController < ApplicationController
  def leave
  end

  def leave_submit
    FeedbackMailer.feedback_email(params).deliver
    flash[:notice] = t('app.feedback.sent')
    render action: "leave"
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/views/feedback/leave.html.erb
<div class="container">
  <div class="row">
    <div class="span8 offset2">
      <%= form_tag feedback_leave_post_path, method: "post", class: "form-horizontal well" do %>
      <legend><%= title "Naujas atsiliepimas" %></legend>

        <div class="control-group">
          <label class="control-label">Jūs esate</label>
          <div class="controls">
            <select name="user_type">
              <options>
                <option value="lazy">-- Pasirinkite --</option>
                <option value="specialist">Specialistas</option>
                <option value="seeker">Ieškantis specialisto</option>
                <option value="other">Kitkas</option>
              </options>
            </select>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label">Atsiliepimo tipas</label>
          <div class="controls">
            <select name="feedback_type">
              <options>
                <option value="lazy">-- Pasirinkite --</option>
                <option value="suggestion">Patarimas</option>
                <option value="missing-category">Trūksta kategorijos</option>
                <option value="complaint-system">Nusiskundimas sistema</option>
                <option value="complaint-specialist">Nusiskundimas specialistu</option>
                <option value="offer">Pasiūlymas</option>
                <option value="spam">Reklama</option>
              </options>
            </select>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label">Jūsų vardas</label>
          <div class="controls">
            <%= text_field_tag "name", nil, class: "input-block-level" %>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label">El. paštas</label>
          <div class="controls">
            <%= email_field_tag "email", nil, class: "input-block-level" %>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label">Atsiliepimas</label>
          <div class="controls">
            <%= text_area_tag "feedback", nil,
                              class: "input-block-level",
                              rows: 5 %>

          </div>
        </div>

        <div class="form-actions">
          <%= submit_tag "Siųsti atsiliepimą", class: "btn btn-success btn-large" %>
        </div>

      <% end %>
    </div>
  </div>
</div>